# Assignment 3 (Week 3)

>**Note**: Late submissions are ***`penalized`***.

## Name: Osarieme Ehimwenma

<br>

### Please show and display all your calculations and results.

In [1]:
# Standard imports
import numpy as np
import pandas as pd

# pandas settings
pd.options.display.max_rows = 1_000
pd.options.display.max_columns = 1_000
pd.options.display.max_colwidth = 1_000

# Black code formatter (Optional)
#%load_ext lab_black

## Qs 1

**a.** Given that 

```python
x = np.linspace(0, 10, 10001)
```

using **ONLY** `NumPy`, write an equation that calculates `y`. `y` is calculated using the equation below:
 
$$
y = \exp^{(\frac{-x}{10})}*\sin{(x)}
$$

<br>

**b.** Write a NumPy code that calculates: 

$$
result = \frac{\sum{((x - \bar{x}) * (y - \bar{y}))}}{\sum{(x - \bar{x})^2}}
$$


`X` and `y` are given below:

```python
rng = np.random.default_rng(seed=5)
X = rng.random(size=(35, 2), dtype=np.float32)
y = rng.random(size=(35, 1), dtype=np.float32)
```

### solution 1a

In [2]:
# Write your solution here
# Qs 1a
x = np.linspace(0,10,10001)
x

y = np.exp(((-x)/10)) * np.sin(x)

y

array([ 0.        ,  0.0009999 ,  0.0019996 , ..., -0.19955634,
       -0.19984539, -0.20013418])

In [3]:
np.exp(((-x)/10))

array([1.        , 0.9999    , 0.99980002, ..., 0.36795302, 0.36791623,
       0.36787944])

In [4]:
np.sin(x)

array([ 0.        ,  0.001     ,  0.002     , ..., -0.54234188,
       -0.54318177, -0.54402111])

In [5]:
y*y

array([0.00000000e+00, 9.99799687e-07, 3.99839499e-06, ...,
       3.98227310e-02, 3.99381794e-02, 4.00536909e-02])

### solution 1b

In [6]:
# Write your solution here
# Qs 1b

# if x and y are given as;
rng = np.random.default_rng(seed=5)
X = rng.random(size=(35, 2), dtype=np.float32)
y = rng.random(size=(35, 1), dtype=np.float32)

In [7]:
x_mean = np.mean(X)
x_mean

0.47818276

In [8]:
y_mean = np.mean(y)
y_mean

0.46238747

In [9]:
numerator = np.sum((X - x_mean) * (y - y_mean))
numerator

-0.20320266

In [10]:
denominator = np.sum(np.square(X - x_mean))
denominator

6.6387873

In [11]:
result = numerator / denominator
result

-0.0306084

## Qs 2

Given the **`4-D`** array below:

```python
rng = np.random.default_rng(seed=5)
X = rng.random(size=(16, 3), dtype=np.float32).reshape(2, 4, 2, 3)
```

Find:

**a.** 0.1777215

**b.** 0.51532555

**c.** 


### Solution 2a

In [31]:
# Write your solution here
# Qs 2a
rng = np.random.default_rng(seed=5)
X = rng.random(size=(16, 3), dtype=np.float32).reshape(2, 4, 2, 3)
X

array([[[[0.67078996, 0.8050028 , 0.0226531 ],
         [0.8079407 , 0.4688518 , 0.51532555]],

        [[0.630234  , 0.2858013 , 0.97952366],
         [0.05393064, 0.2779237 , 0.38336885]],

        [[0.5711843 , 0.40847313, 0.13106084],
         [0.04527509, 0.00101531, 0.04875767]],

        [[0.14881468, 0.999176  , 0.19098222],
         [0.652369  , 0.7502588 , 0.23451018]]],


       [[[0.2822373 , 0.4349475 , 0.2632376 ],
         [0.9741862 , 0.1777215 , 0.89767754]],

        [[0.7976887 , 0.844231  , 0.11573017],
         [0.39240456, 0.6280302 , 0.49302292]],

        [[0.6658664 , 0.67668927, 0.6629263 ],
         [0.0608027 , 0.9590993 , 0.5555961 ]],

        [[0.90351176, 0.2714516 , 0.36151814],
         [0.87965107, 0.18690252, 0.06421435]]]], dtype=float32)

In [32]:
X[1,:1,1,1]

array([0.1777215], dtype=float32)

In [36]:
# Write your solution here
# Qs 2b
X[0,:1,1,2]

array([0.51532555], dtype=float32)

## Qs 3

Using Pandas, find the number of employees that:

**a.** Write a query/code that determines the employees that are older than **30** years and their job role is either **manager** or **research director** or **manufacturing director** and have a **performance rating** greater than **3**.

**b.** Create a new column that combines `technical degree`, `other` and `human resources` from **`education field`** into a new label called **others**. i.e the resulting column should have four (4) unique labels namely: **`life sciences`**, **`medical`**, **`marketing`** and **`others`**. Hint: Use `.apply()`

**c.** Write a code that splits the data into **numerical** and **categorical** data. Display the **first 5 rows** of your results on separate cells using `.head()`. 

#### The data can be found [here](https://drive.google.com/file/d/1SSOdAGm0nCpPhKCqA1rgW00mwpseL7Dj/view?usp=share_link)

In [24]:
fp = "C:/Users/HP/Desktop/SGA1_4/HR_Employee_reduced.csv"
data = pd.read_csv(fp)

print(f"Shape of Data: {data.shape}\n")


# Create DataFrame
df = pd.DataFrame(data)
df.head()

Shape of Data: (1470, 17)



Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

                 JobRole  EnvironmentSatisfaction  Gender  PerformanceRating  \
0        Sales Executive                        2  Female                  3   
1     Research Scientist                        3    Male                  4   
2  Laboratory Technician                        4    Male                  3   
3     Research Scientist                        4  Female                  3   
4  Laboratory Technician                        1    Male                  3   

   HourlyRate  JobInvolvement  JobLevel  
0          94               3         2  
1          61               2         2  
2          92               2         1  
3          56               3         1  
4          40               3         1

### solution 3a

In [25]:
# Write your solution here
# Qs 3a
df.query("Age > 30 & PerformanceRating > 3 & JobRole == 'Research Director' | JobRole == 'Manager' | JobRole == 'Manufacturing Director' ")[["Age", "PerformanceRating", "JobRole"]]

Age  PerformanceRating                 JobRole
8      38                  4  Manufacturing Director
15     29                  3  Manufacturing Director
18     53                  3                 Manager
20     24                  3  Manufacturing Director
25     53                  3                 Manager
29     46                  3                 Manager
59     37                  3  Manufacturing Director
60     32                  4  Manufacturing Director
65     55                  3                 Manager
66     36                  3  Manufacturing Director
75     31                  4  Manufacturing Director
84     34                  3  Manufacturing Director
85     56                  3  Manufacturing Director
105    59                  4                 Manager
112    54                  3                 Manager
116    34                  3                 Manager
119    43                  3                 Manager
129    49                  3  Manufacturing Director
135    36                  4  Manufacturing Director
136    51                  3  Manufacturing Director
147    41                  3                 Manager
155    29                  3  Manufacturing Director
156    51                  3  Manufacturing Director
165    50                  3                 Manager
184    53                  3  Manufacturing Director
186    40                  3                 Manager
188    34                  3  Manufacturing Director
190    52                  3                 Manager
192    35                  3  Manufacturing Director
194    45                  4                 Manager
197    42                  3  Manufacturing Director
198    38                  3  Manufacturing Director
199    38                  3  Manufacturing Director
200    27                  3  Manufacturing Director
201    49                  3  Manufacturing Director
211    30                  4  Manufacturing Director
215    41                  3                 Manager
224    31                  3  Manufacturing Director
231    42                  3                 Manager
233    50                  3                 Manager
235    43                  4                 Manager
237    52                  3                 Manager
244    45                  3                 Manager
247    34                  3  Manufacturing Director
249    45                  3  Manufacturing Director
250    37                  3  Manufacturing Director
255    25                  3  Manufacturing Director
263    46                  3                 Manager
270    55                  3                 Manager
271    47                  3                 Manager
276    35                  3                 Manager
278    26                  4  Manufacturing Director
299    51                  3  Manufacturing Director
300    41                  3                 Manager
313    33                  3                 Manager
314    39                  3                 Manager
325    31                  4  Manufacturing Director
326    39                  3                 Manager
340    37                  3  Manufacturing Director
342    31                  3  Manufacturing Director
344    35                  3  Manufacturing Director
346    41                  3  Manufacturing Director
352    48                  4                 Manager
365    46                  3  Manufacturing Director
379    55                  3                 Manager
389    37                  3  Manufacturing Director
394    31                  3  Manufacturing Director
400    39                  3                 Manager
406    52                  3  Manufacturing Director
408    52                  3                 Manager
410    30                  4  Manufacturing Director
411    60                  3                 Manager
412    46                  3  Manufacturing Director
417    40                  3                 Manager
424    57                  3   

In [26]:
# Write your solution here
# Qs 3b

### Solution 3c

In [30]:
# Write your solution here
# Qs 3c
df_numerical = df.select_dtypes(include= np.number)
df_numerical.head()

#numerical_col = [(df_Ibm_data.select_dtypes(include = np.number).columns)]
#categorical_col = [(df_Ibm_data.select_dtypes(include = object).columns)]

Age  DailyRate  DistanceFromHome  Education  EmployeeCount  EmployeeNumber  \
0   41       1102                 1          2              1               1   
1   49        279                 8          1              1               2   
2   37       1373                 2          2              1               4   
3   33       1392                 3          4              1               5   
4   27        591                 2          1              1               7   

   EnvironmentSatisfaction  PerformanceRating  HourlyRate  JobInvolvement  \
0                        2                  3          94               3   
1                        3                  4          61               2   
2                        4                  3          92               2   
3                        4                  3          56               3   
4                        1                  3          40               3   

   JobLevel  
0         2  
1         2  
2         1  
3         1  
4         1

In [29]:
df_categorical = df.select_dtypes(include= "object")
df_categorical.head()

Attrition     BusinessTravel              Department EducationField  \
0       Yes      Travel_Rarely                   Sales  Life Sciences   
1        No  Travel_Frequently  Research & Development  Life Sciences   
2       Yes      Travel_Rarely  Research & Development          Other   
3        No  Travel_Frequently  Research & Development  Life Sciences   
4        No      Travel_Rarely  Research & Development        Medical   

                 JobRole  Gender  
0        Sales Executive  Female  
1     Research Scientist    Male  
2  Laboratory Technician    Male  
3     Research Scientist  Female  
4  Laboratory Technician    Male

## Qs 4

Given the data below:

```python
salary = [74454, 54900, 76182, 56221, 81254, 75900, 67122, 62426, 61553,
       77070, 67587, 50095, 75820, 68174, 79069]
students = [
    "Sadiq",
    "Aminu",
    "Udensi",
    "Olayiwola",
    "Ukpeh",
    "Akinbade",
    "Ezeofor",
    "Oludele",
    "Gbenga",
    "Edgar",
    "Worlu",
    "Magbuwe",
    "Atte",
    "Orogun",
    "Bamigbade"
]

roles = [
    "Data Engineer",
    "Data Scientist",
    "DevOps Engineer",
    "Research Engineer",
    "Analytical Engineer",
    "Data Analyst",
    "ML Engineer",
    "DevOps Engineer",
    "Analytical Engineer",
    "Data Scientist",
    "MLOps Engineer",
    "Data Engineer",
    "Data Scientist",
    "ML Engineer",
    "Research Engineer",
]
```

**a.** Create a `DataFrame` using the lists above. The column names should be: `name` , `job_role` and `salary`.

**b.** Create a new column **`title`** that has has 2 new labels `Engineer` and `Analyst/Scientist` if the person has `engineer` or `analyst/scientist` in their job role.

**c.** What is the mean and median salary per `title`?

### solution 4a

In [18]:
# Write your solution here
# Qs 4a
data = {
    "salary":[
        74454, 54900, 76182, 56221, 81254, 75900, 67122, 62426, 61553,
       77070, 67587, 50095, 75820, 68174, 79069
    ],
    "Name": [
        "Sadiq",
        "Aminu",
        "Udensi",
        "Olayiwola",
        "Ukpeh",
        "Akinbade",
        "Ezeofor",
        "Oludele",
        "Gbenga",
        "Edgar",
        "Worlu",
        "Magbuwe",
        "Atte",
        "Orogun",
        "Bamigbade"
    ],

    "Job_roles": [
        "Data Engineer",
        "Data Scientist",
        "DevOps Engineer",
        "Research Engineer",
        "Analytical Engineer",
        "Data Analyst",
        "ML Engineer",
        "DevOps Engineer",
        "Analytical Engineer",
        "Data Scientist",
        "MLOps Engineer",
        "Data Engineer",
        "Data Scientist",
        "ML Engineer",
        "Research Engineer",
    ]
}

# Create DataFrame
df = pd.DataFrame(data)
df

salary       Name            Job_roles
0    74454      Sadiq        Data Engineer
1    54900      Aminu       Data Scientist
2    76182     Udensi      DevOps Engineer
3    56221  Olayiwola    Research Engineer
4    81254      Ukpeh  Analytical Engineer
5    75900   Akinbade         Data Analyst
6    67122    Ezeofor          ML Engineer
7    62426    Oludele      DevOps Engineer
8    61553     Gbenga  Analytical Engineer
9    77070      Edgar       Data Scientist
10   67587      Worlu       MLOps Engineer
11   50095    Magbuwe        Data Engineer
12   75820       Atte       Data Scientist
13   68174     Orogun          ML Engineer
14   79069  Bamigbade    Research Engineer

### solution 4b

In [19]:
# Write your solution here
# Qs 4b
def data (job):
    if job == "Data Engineer":
        return "Engineer"
    elif job == "DevOps Engineer":
        return "Engineer"
    elif job == "Research Engineer":
        return "Engineer"
    elif job == "Analytical Engineer":
        return "Engineer"
    elif job == "ML Engineer":
        return "Engineer"
    elif job == "MLOps Engineer":
        return "Engineer"
    else:
        return "Analyst/Scientist"
    
df["title"]=df.Job_roles.apply(data)
df

salary       Name            Job_roles              title
0    74454      Sadiq        Data Engineer           Engineer
1    54900      Aminu       Data Scientist  Analyst/Scientist
2    76182     Udensi      DevOps Engineer           Engineer
3    56221  Olayiwola    Research Engineer           Engineer
4    81254      Ukpeh  Analytical Engineer           Engineer
5    75900   Akinbade         Data Analyst  Analyst/Scientist
6    67122    Ezeofor          ML Engineer           Engineer
7    62426    Oludele      DevOps Engineer           Engineer
8    61553     Gbenga  Analytical Engineer           Engineer
9    77070      Edgar       Data Scientist  Analyst/Scientist
10   67587      Worlu       MLOps Engineer           Engineer
11   50095    Magbuwe        Data Engineer           Engineer
12   75820       Atte       Data Scientist  Analyst/Scientist
13   68174     Orogun          ML Engineer           Engineer
14   79069  Bamigbade    Research Engineer           Engineer

### Solution 4c 

In [20]:
# Write your solution here
# Qs 4c
columns = ["salary", "title"]

df[columns].mean()

salary    68521.8
dtype: float64

In [21]:
columns = ["salary", "title"]

df[columns].median()

salary    68174.0
dtype: float64